version: '3.7'


services:
  re:
    image: redis
    container_name: re
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always 
    container_name: db
    command: -p 5435
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
  
  api:
    container_name: qrmenu
    build: 
      context: ./qr-sys
    image: dchnkoo/qr-sys
    command: ["./app.sh"]
    env_file:
      - qr-sys/.env
    ports:
      - "8000:8080"
    depends_on:
      - db
      - re

  keysetter:
    container_name: key
    image: dchnkoo/secret-setter
    build: 
      context: ./qr-sys
    command: ["python3", "-m", "app.SECRET_KEY.generate", "--set-secret"]
    env_file:
      - qr-sys/.env
    depends_on:
      - re
  

  celery:
    build: 
      context: ./qr-sys
    image: dchnkoo/celery
    container_name: celery
    command: ["./celery.sh", "celery"]
    env_file:
      - qr-sys/.env
    depends_on:
      - re

  flower:
    build: 
      context: ./qr-sys
    image: dchnkoo/flower
    container_name: flower
    command: ["./celery.sh", "flower"]
    env_file:
      - qr-sys/.env
    depends_on:
      - re
      - celery
    ports:
      - "5555:5555"