version: '3.7'


services:
  re:
    image: redis
    container_name: re
    command: redis-server --requirepass testpass
    ports:
      - "6379:6379"
    networks:
      - new_network

  db:
    image: postgres
    restart: always 
    container_name: db
    command: -p 5435
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - new_network
  
  api:
    container_name: api
    image: dchnkoo/qr-sys
    build: ./qr-sys
    env_file:
      - qr-sys/.env
    depends_on:
      - db
      - re
    networks:
      - new_network

  nginx:
    image: nginx:latest
    container_name: nginx
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/nginx.conf
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - api
    networks:
      - new_network

networks:
  new_network:
    external: true
